apiVersion: v1
kind: Service
metadata:
  name: ms-mailing
  labels:
    app: ms-mailing
spec:
  type: ClusterIP
  ports:
    - name: "web"
      port: 3333
      targetPort: 3333
  selector:
    app: ms-mailing
