apiVersion: v1
kind: Secret
metadata:
  name: ms-mailing-secret
type: Opaque
data:
  APP_KEY: "TzJnNlpIVWY4TXZBRW5hdFVsSW5DY3NBam80T0phSTA="
  RABBITMQ_USER: "Z3Vlc3Q="
  RABBITMQ_PASSWORD: "Z3Vlc3Q="
  SMTP_USERNAME: "a2FyYWt1c3lhc2luMTlAZ21haWwuY29t"
  SMTP_PASSWORD: "aGJteWl4YnJvbmRiaWRhcw=="


